### ISSUE TITLE
InvokeAI webUI doesn't open

### ISSUE THREAD

**Issue by lilcdj** [LykosAI/StabilityMatrix#399]
I installed InvokeAI package and it looks start well but, when i open WebUI, it doesn't show InvokeUI.

**Comment by xenuser** [comment]
AFAIK InvokeAI removed the UI from the main branch. The UI installation is now separated from the backend. This is one of the major changes in 3.6. Here is the PR/issue with more details: https://github.com/invoke-ai/InvokeAI/pull/5253
StabilityMatrix needs to reflect that change and take care of this as well, IMHO.

**Comment by xenuser** [comment]
Edit: A new installation of InvokeAI using the latest available version of StabilityMatrix also results in "UI not found".

**Comment by LeeLorenzSr** [comment]
Looking into this, it's because InvokeAI split their repo, so the WebUI has to be installed/built separately. Very annoying. StabilityMatrix will have to make some sort of adjustments to install both components. InvokeAI 3.6 looks amazing.

**Comment by tkoenig89** [comment]
The latest update (for StabilityMatrix) fixed this for me. It seems to install/setup the webui when launching, so we can use InvokeAI as before.

**Comment by Razunter** [comment]
I'm getting StableDiffusion-StabilityMatrix\Data\Packages\InvokeAI\invokeai-root\models\core\convert\CLIP-ViT-bigG-14-laion2B-39B-b160k is missing

**Comment by ionite34** [comment]
Should be fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.7.9 where we added the new node build steps for the InvokeAI frontend.

**Comment by Uriel1339** [comment]
This issue persists in 2.12.4 Windows 11:
https://github.com/LykosAI/StabilityMatrix/releases/latest/download/StabilityMatrix-win-x64.zip

'[InvokeAI]::WARNING --> No UI found at C:\<local path>\StabilityMatrix\Packages\InvokeAI\invokeai\frontend\web/dist, skipping UI mount'

**Comment by iopenet** [comment]
Does anyone care about wasting bandwidth anymore ?

Besides the lingering issues, some, if not most, could be solved
if StabilityMatrix checked compatibility before anything else,
in order to avoid wasting bandwidth and time downloading a package that is doomed to fail.

Another important UX issue is that "Open Web UI" should only be active when the package is ready.

**Comment by aesanchezgh** [comment]
I have that same error
