### ISSUE TITLE
ComfyUI problem?

### ISSUE THREAD

**Issue by LoicSuply975** [LykosAI/StabilityMatrix#825]
Hi, I recently update ComfyUI, when I launch it, it show a error massage:
The JSON value could not be converted to System.Collections.Generic.List'1[System.String].
Path: $[1] LineNumber: 0 BytePositionInLine: 92

**Comment by Jojo-xqt** [comment]
I have the same issue; I thought I was the only one experiencing it.

**Comment by Stan-UWU** [comment]
This is happening to me as well, can't figure out how to fix it.

**Comment by mohnjiles** [comment]
Sorry folks, this was an issue on our end with the latest versions of ComfyUI. This should be fixed if you upgrade to the [latest version of Stability Matrix (v2.11.7)](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.7)

**Comment by search-acumen** [comment]
Still getting the error after updating to 2.11.7. (Portable version)

**Comment by LoicSuply975** [comment]
> Sorry folks, this was an issue on our end with the latest versions of ComfyUI. This should be fixed if you upgrade to the [latest version of Stability Matrix (v2.11.7)](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.7)

This is finally fixed for me, thanks! 👍
